### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by shanuka** [vincentbrison/vb-android-app-quality#14]
> java.lang.IllegalArgumentException: Unable to exclude rules [ProtectLogD]; perhaps the rule name is mispelled?

**Comment by vincentbrison** [comment]
Hi,
How I can reproduce this issue ?

**Comment by Armaxis** [comment]
I also got this error. Just followed [this guide](http://vincentbrison.com/2014/07/19/how-to-improve-quality-and-syntax-of-your-android-code/#Findbugs) - and got error. 
Maybe it's because I'm using gradle plugin 1.3.0?

Here is a stacktrace of running gradle task:
```
Caused by: : java.lang.IllegalArgumentException: Unable to exclude rules [LongMethodName]; perhaps the rule name is mispelled?
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:77)
        at org.gradle.api.internal.project.AntBuilderDelegate.nodeCompleted(DefaultIsolatedAntBuilder.groovy:177)
        at org.gradle.api.plugins.quality.Pmd$_run_closure2.doCall(Pmd.groovy:137)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
        at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
        at org.gradle.api.internal.project.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.groovy:108)
        at org.gradle.api.internal.project.IsolatedAntBuilder$execute$0.call(Unknown Source)
        at org.gradle.api.plugins.quality.Pmd.run(Pmd.groovy:135)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
Caused by: java.lang.IllegalArgumentException: Unable to exclude rules [LongMethodName]; perhaps the rule name is mispelled?
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetReferenceNode(RuleSetFactory.java:321)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:263)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:220)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:165)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:130)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:115)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:113)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:263)
        at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:46)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        ... 78 more
```

**Comment by vincentbrison** [comment]
Thanks for the details, I will look into this.

**Comment by sewerk** [comment]
From my analyses this is caused by gradle version: gradle-2.4-all.zip as it uses newer version of PMD.
To reproduce change value in gradle-wrapper.properties.

To fix the build error you can simple remove the rules spelled in error from config file config/pmd/pmd-rulset.xml

**Comment by vincentbrison** [comment]
Thanks for the detailed report :). I am currently in vacation and can't fix
this before the next week. Btw feel free to propose the fix as a merge
request.
BR.
